---

name: build and deliver cowsay app

on:
  push:

jobs:
  build:
    name: build go code into binary
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'

      - run: go version

      - run: |
          go mod init github.com/midoufkir/go-cowsay    
          go mod tidy
          go run .
          go build -o bin/cowsay .

      - name: Upload static files as artifact
        id: deployment
        uses:  actions/upload-artifact@v4
        with:
          path: bin/
          name: cowsaybin

  deploy:
    name: deploy on my self hosted
    needs: build
    runs-on: self-hosted
    steps:
      - run: ls